### ISSUE TITLE
rename the jobs

### ISSUE THREAD

**Issue by Raboo** [kastenhq/kubestr#100]
Hi,

I find it a bit confusing that the jobs are named like read_iops and read_bw. Aren't those the same thing just with different block sizes? Wouldn't it be better to have the jobs named like randread_4K, randread_128K, randwrite_4K, randwrite_128K instead?

Results produce both iops and bandwidth (and perhaps in the future latency as well) on 4K and 128K. Likely you might even get a slightly higher bandwidth running 1M block size. I think it's important to highlight that you are not just measuring bandwidth in 128K even though higher block size usually results in higher bandwidth.

**Comment by bathina2** [comment]
@Raboo Those are only the default tests that we run. We understand that everyones needs are different and they may be testing different things. For that reason we have the `-f, --fiofile` option where a user can specify their own FIO configuration (like specifying a 1M block size).
