### ISSUE TITLE
No release assets for v0.4.32 

### ISSUE THREAD

**Issue by frezbo** [kastenhq/kubestr#108]
Release [v0.4.32](https://github.com/kastenhq/kubestr/releases/tag/v0.4.32) is missing the binary assets

**Comment by ihcsim** [comment]
Thanks for bringing this up. We just cut [v0.4.33](https://github.com/kastenhq/kubestr/releases/tag/v0.4.33). Give it a try and let us know what you think. We are on [slack](kanisterio.slack.com).
