### ISSUE TITLE
No binaries for release v0.4.38

### ISSUE THREAD

**Issue by alexellis** [kastenhq/kubestr#160]
Hi, there are no binaries for release v0.4.38

This breaks `arkade get kubestr`

cc @MichaelCade 

Could you delete the release or add the proper binaries to it? Perhaps some automation failed

Alex

**Comment by bathina2** [comment]
Working on a fix for this, the creation and publishing process is automated. However go_releaser deprecated `archive.replacements` which broke the automation.
https://goreleaser.com/deprecations/#expired-deprecation-notices_1

**Comment by bathina2** [comment]
Resolved in latest release - https://github.com/kastenhq/kubestr/releases/tag/v0.4.41

**Comment by alexellis** [comment]
Thanks for the fix, we'll enable kubestr in the next release of arkade, or someone can send a PR to uncomment the code.
