### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by osaffer** [kastenhq/kubestr#62]
Hi,

 ./kubestr

**************************************
  _  ___   _ ___ ___ ___ _____ ___
  | |/ / | | | _ ) __/ __|_   _| _ \
  | ' <| |_| | _ \ _|\__ \ | | |   /
  |_|\_\\___/|___/___|___/ |_| |_|_\

Explore your kubernetes storage options
**************************************
Kubernetes Version Check:
  Valid kubernetes version (v1.20.2)  -  OK

RBAC Check:
  Kubernetes RBAC is enabled  -  OK

Aggregated Layer Check:
  The Kubernetes Aggregated Layer is enabled  -  OK

W0402 10:53:35.051737   73756 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
Available Storage Provisioners:

  rook-ceph.cephfs.csi.ceph.com:
    Can't find the CSI snapshot group api version.
    This is a CSI driver!
    (The following info may not be up to date. Please check with the provider for more information.)
    Provider:            CephFS
    Website:             https://github.com/ceph/ceph-csi
    Description:         A Container Storage Interface (CSI) Driver for CephFS
    Additional Features: Expansion, Snapshot, Clone

    Storage Classes:
      * rook-cephfs

    To perform a FIO test, run-
      ./kubestr fio -s <storage class>

    This provisioner supports snapshots, however no Volume Snaphsot Classes were found.
 

./kubestr fio -s rook-cephfs
PVC created kubestr-fio-pvc-klnpv
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14056a3]

goroutine 1 [running]:
github.com/kastenhq/kubestr/pkg/fio.(*FIOrunner).RunFioHelper.func3(0xc000707b58, 0x0, 0xc000282e40)
        /github/workspace/pkg/fio/fio.go:138 +0x33
github.com/kastenhq/kubestr/pkg/fio.(*FIOrunner).RunFioHelper(0xc000707b58, 0x19d5f40, 0xc0001b05a0, 0xc000282e40, 0x0, 0x199a6e0, 0xc0006180a0)
        /github/workspace/pkg/fio/fio.go:141 +0x9f0
github.com/kastenhq/kubestr/pkg/fio.(*FIOrunner).RunFio(0xc000031b58, 0x19d5f40, 0xc0001b05a0, 0xc000282e40, 0x2560360, 0x7f40eee877d0, 0x0)
        /github/workspace/pkg/fio/fio.go:91 +0x14b
github.com/kastenhq/kubestr/cmd.Fio(0x19d5f40, 0xc0001b05a0, 0x0, 0x0, 0x7ffd1d078dd4, 0xb, 0x17829ca, 0x5, 0x1784087, 0x7, ...)
        /github/workspace/cmd/rootCmd.go:160 +0x1ac
github.com/kastenhq/kubestr/cmd.glob..func2(0x2546840, 0xc000130ea0, 0x0, 0x2)
        /github/workspace/cmd/rootCmd.go:59 +0x146
github.com/spf13/cobra.(*Command).execute(0x2546840, 0xc000130e80, 0x2, 0x2, 0x2546840, 0xc000130e80)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x25465a0, 0x0, 0x184000, 0xc000182058)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/kastenhq/kubestr/cmd.Execute(...)
        /github/workspace/cmd/rootCmd.go:105
main.Execute(...)
        /github/workspace/main.go:29
main.main()
        /github/workspace/main.go:24 +0x2f

**Comment by pasmon** [comment]
Got pretty much the same issue with our "local-storage" SC, "standard" worked fine:
```
Kubernetes Version Check:
  Valid kubernetes version (v1.15.3)  -  OK

RBAC Check:
  Kubernetes RBAC is enabled  -  OK

Aggregated Layer Check:
  The Kubernetes Aggregated Layer is enabled  -  OK

Available Storage Provisioners:

  kubernetes.io/no-provisioner:
    This is an in tree provisioner.

    Storage Classes:
      * local-storage

    To perform a FIO test, run-
      ./kubestr fio -s <storage class>

  kubernetes.io/cinder:
    This is an in tree provisioner.

    Storage Classes:
      * standard

    To perform a FIO test, run-
      ./kubestr fio -s <storage class>

at 10:32:27 ❯ kubestr fio -s local-storage
PVC created kubestr-fio-pvc-cvdnd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14056a3]

goroutine 1 [running]:
github.com/kastenhq/kubestr/pkg/fio.(*FIOrunner).RunFioHelper.func3(0xc0004a7b58, 0x0, 0xc000282240)
	/github/workspace/pkg/fio/fio.go:138 +0x33
github.com/kastenhq/kubestr/pkg/fio.(*FIOrunner).RunFioHelper(0xc0004a7b58, 0x19d5f40, 0xc00007e600, 0xc000282240, 0x0, 0x199a6e0, 0xc00033f560)
	/github/workspace/pkg/fio/fio.go:141 +0x9f0
github.com/kastenhq/kubestr/pkg/fio.(*FIOrunner).RunFio(0xc000031b58, 0x19d5f40, 0xc00007e600, 0xc000282240, 0x2560360, 0x7fb9ae8467d0, 0x0)
	/github/workspace/pkg/fio/fio.go:91 +0x14b
github.com/kastenhq/kubestr/cmd.Fio(0x19d5f40, 0xc00007e600, 0x0, 0x0, 0x7fffc51b21fd, 0xd, 0x17829ca, 0x5, 0x1784087, 0x7, ...)
	/github/workspace/cmd/rootCmd.go:160 +0x1ac
github.com/kastenhq/kubestr/cmd.glob..func2(0x2546840, 0xc00000e880, 0x0, 0x2)
	/github/workspace/cmd/rootCmd.go:59 +0x146
github.com/spf13/cobra.(*Command).execute(0x2546840, 0xc00000e860, 0x2, 0x2, 0x2546840, 0xc00000e860)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x25465a0, 0x0, 0x60e00, 0xc000044298)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/kastenhq/kubestr/cmd.Execute(...)
	/github/workspace/cmd/rootCmd.go:105
main.Execute(...)
	/github/workspace/main.go:29
main.main()
	/github/workspace/main.go:24 +0x2f


```

**Comment by bathina2** [comment]
@osaffer  @pasmon Thanks for reporting the issue. I have identified the issue, there seems to be a misplaced `defer` statement. It looks like pod creation may have failed. I will push a fix and it will be included in the next release.

**Comment by bathina2** [comment]
Included as part of this release https://github.com/kastenhq/kubestr/releases/tag/v.0.4.15
