### ISSUE TITLE
registered csi drivers

### ISSUE THREAD

**Issue by travisghansen** [kastenhq/kubestr#70]
Cool tool! I'm the author of https://github.com/democratic-csi/democratic-csi and plan to use this for some testing. I noticed when running the binary and it detects drivers for me it shows this:

```
kubestr-v0.4.16

**************************************
  _  ___   _ ___ ___ ___ _____ ___
  | |/ / | | | _ ) __/ __|_   _| _ \
  | ' <| |_| | _ \ _|\__ \ | | |   /
  |_|\_\\___/|___/___|___/ |_| |_|_\

Explore your Kubernetes storage options
**************************************
Kubernetes Version Check:
  Valid kubernetes version (v1.19.4)  -  OK

RBAC Check:
  Kubernetes RBAC is enabled  -  OK

Aggregated Layer Check:
  The Kubernetes Aggregated Layer is enabled  -  OK

Available Storage Provisioners:

  org.democratic-csi.nfs:
    This might be a CSI Driver. But it is not publicly listed.

    Storage Classes:
      * zfs-nfs

    To perform a FIO test, run-
      ./kubestr fio -s <storage class>

  org.democratic-csi.nfs-client:
    This might be a CSI Driver. But it is not publicly listed.

    Storage Classes:
      * nfs-client

    To perform a FIO test, run-
      ./kubestr fio -s <storage class>

  org.democratic-csi.iscsi:
    This might be a CSI Driver. But it is not publicly listed.

    Storage Classes:
      * zfs-iscsi

    To perform a FIO test, run-
      ./kubestr fio -s <storage class>

```

What does it take to be 'publicly listed' and what additional information is shown if it is? In the case of `democratic-csi` it's up to the user to decide what the driver names are (although generally they'll follow the syntax above) as it can be deployed any number of times with slightly different configurations.

**Comment by bathina2** [comment]
@travisghansen Thanks for the feedback! We use information derived from [here](https://raw.githubusercontent.com/kubernetes-csi/docs/master/book/src/drivers.md). Currently we do an exact match on the driver name but maybe we can do some sort of pattern matching to get better results.

**Comment by travisghansen** [comment]
Ok, a regex would probably do the trick and I am listed there.

What extra information is output when a match is found?

**Comment by bathina2** [comment]
Right now we display the Provider name, website, description and additional features. I also have a disclaimer saying the information may be out of date and to refer to the providers website for more information.

**Comment by travisghansen** [comment]
I see. It appears there are several others that have regex style approaches. Would you be interested in working jointly to add that feature so those work?

**Comment by bathina2** [comment]
@travisghansen Give me a couple of days to see if we can have an engineer address this. Otherwise, we would love to work with you to add that feature.

**Comment by bathina2** [comment]
@travisghansen If you want to take a shot at it please go ahead. You can run `go generate` at the top level to generate the latest driver list. Please make sure to check that in as well.

**Comment by travisghansen** [comment]
I’m a go ignorant so probably not the best choice to implement :(

**Comment by bathina2** [comment]
No worries, bit swamped at the moment but I'll see if someone in our organization can take a look. Otherwise I'll be able to get to it in a week

**Comment by bathina2** [comment]
Thanks @sukhil-suresh for working on this. @travisghansen  Can you try it out with our latest release and let us know what you see?

**Comment by travisghansen** [comment]
@bathina2 yeah works great! Thanks for being willing to add the feature!
