### ISSUE TITLE
issue while pulling image in private network of organization

### ISSUE THREAD

**Issue by Rajpratik71** [kastenhq/kubestr#81]
Behind the proxied network, Pods stay in the "ImagePullBackOff" state due to image pull error.

Adding support for overriding default image location can fix the issue from the tool side.

**Comment by maakuth** [comment]
It seems that you might want to have a look at the --image command line flag.

**Comment by Rajpratik71** [comment]
@maakuth  @bathina2  does "kubestr" supports this ?

**Comment by bathina2** [comment]
@Rajpratik71 Sorry for the late reply, for both the `fio` and the `csicheck` sub commands we support passing in a local image.
